#!/bin/bash

echo "🚀 Setting up SendGrid Email Service"
echo "===================================="
echo ""

echo "📝 Step 1: Create SendGrid Account"
echo "1. Go to: https://sendgrid.com"
echo "2. Click 'Start for Free'"
echo "3. Sign up with: almaryahrostery@gmail.com"
echo "4. Verify your email"
echo ""

echo "🔑 Step 2: Generate API Key"
echo "1. Login to SendGrid Dashboard"
echo "2. Go to: Settings > API Keys"
echo "3. Click 'Create API Key'"
echo "4. Name it: 'Al Marya Rostery App'"
echo "5. Select: 'Full Access' or 'Mail Send'"
echo "6. Copy the API Key (starts with 'SG.')"
echo ""

echo "⚙️ Step 3: Update Configuration"
echo "Once you have the API Key, I'll update the .env file:"
echo ""
echo "EMAIL_PROVIDER=sendgrid"
echo "SENDGRID_API_KEY=your_api_key_here"
echo "EMAIL_FROM_ADDRESS=almaryahrostery@gmail.com"
echo ""

echo "✅ Benefits of SendGrid:"
echo "• More reliable than Gmail SMTP"
echo "• 100 free emails per day"
echo "• Better delivery rates"
echo "• Professional email service"
echo "• Detailed analytics"
echo ""

echo "🔄 Alternative: Continue with Gmail"
echo "If you prefer to fix Gmail instead:"
echo "1. Check 2FA is enabled: https://myaccount.google.com/security"
echo "2. Generate new App Password: https://myaccount.google.com/apppasswords"
echo "3. Wait 10-15 minutes for Google to propagate changes"
echo "4. Try again"
echo ""

echo "Would you like to:"
echo "A) Set up SendGrid (recommended - 5 minutes)"
echo "B) Continue troubleshooting Gmail (uncertain timeline)"
echo ""
echo "Let me know your choice!"
